apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-db-config
  namespace: lab4
  labels:
    lab: lab4
    component: database
data:
  POSTGRES_DB: lab4_app
  POSTGRES_HOST: postgres-service.lab4.svc.cluster.local
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-gateway-config
  namespace: lab4
  labels:
    lab: lab4
    component: gateway
data:
  LLM_SERVICE_URL: http://llm-service.lab4.svc.cluster.local:9000
  LLM_TIMEOUT_SECONDS: "15"
  HISTORY_LIMIT: "6"
  LOG_LEVEL: INFO
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-llm-config
  namespace: lab4
  labels:
    lab: lab4
    component: llm
data:
  MISTRAL_MODEL: mistral-large-latest
  LLM_MAX_ITEMS: "3"
  LOG_LEVEL: INFO

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-tg-bot-config
  namespace: lab4
  labels:
    lab: lab4
    component: tg-bot
data:
  GATEWAY_URL: http://gateway-service.lab4.svc.cluster.local:8080
  BOT_GATEWAY_TIMEOUT: "30"
  LOG_LEVEL: INFO

