apiVersion: v1
kind: Secret
metadata:
  name: lab4-secrets
  namespace: lab4
  labels:
    lab: lab4
    component: security
type: Opaque
stringData:
  POSTGRES_USER: lab4_user
  POSTGRES_PASSWORD: lab4_password
  DATABASE_URL: postgresql+asyncpg://lab4_user:lab4_password@postgres-service.lab4.svc.cluster.local:5432/lab4_app
  MISTRAL_API_KEY: -----
  BOT_TOKEN: -----

