apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app: nextcloud
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "change_me_admin"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password"
